### ISSUE TITLE
Safari cannot download this file when downloading pass

### ISSUE THREAD

**Issue by martyndix** [includable/php-pkpass#116] opened 2022-09-18 12:31 UTC
### Expected Behavior
Pass is downloaded when navigating to URL.

### Actual Behavior
Pass is not generated and error message is shown "Safari cannot download this file". I have been using pkpass repository for years with no problems, just now it has started to display this message. Only change seems to be iOS 16 release.

### Steps to Reproduce the Problem

  1. Navigate to URL to generate pass.
  2. Message is displayed
  3.

**Comment by martyndix** [comment] 2022-09-18 12:33
I have tried to update the AppleWWDRCA.pem certificate but I do not think it is out of date. Not sure what else to try. Any assistance would be greatly appreciated.
Thank you in advance.

**Comment by tschoffelen** [comment] 2022-09-19 13:33
I can't reproduce this, works fine for me on iPhone and Mac. Are you using the final iOS 16 version and not a beta version?

There is information in the README on how to debug using the Console application, this should show you what error is occurring exactly on the device.

**Comment by tschoffelen** [comment] 2022-10-25 08:30
I think this might have been related to the outdated WWDR cert as mentioned in #119 - this is fixed now.

**Closed by tschoffelen** 2022-10-25 08:30 UTC
